package tabs.calendar;

import org.junit.*;
import static org.junit.Assert.*;

/**
 * The class <code>CalendarViewFactoryTest</code> contains tests for the class <code>{@link CalendarViewFactory}</code>.
 *
 * @generatedBy CodePro at 5/1/11 6:24 PM
 * @author zafar.khaydarov
 * @version $Revision: 1.1 $
 */
public class CalendarViewFactoryTest {
	/**
	 * Run the CalendarView createCalendarView() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 5/1/11 6:24 PM
	 */
	@Test
	public void testCreateCalendarView_1()
		throws Exception {

		CalendarView result = CalendarViewFactory.createCalendarView();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.RuntimeException: Stub!
		//       at android.content.Context.<init>(Context.java:4)
		//       at android.content.ContextWrapper.<init>(ContextWrapper.java:5)
		//       at android.view.ContextThemeWrapper.<init>(ContextThemeWrapper.java:5)
		//       at android.app.Activity.<init>(Activity.java:6)
		//       at android.app.ActivityGroup.<init>(ActivityGroup.java:5)
		//       at android.app.TabActivity.<init>(TabActivity.java:5)
		//       at caao.com.Main_activity.<init>(Main_activity.java:57)
		//       at caao.com.Main_activityFactory.createMain_activity(Main_activityFactory.java:29)
		//       at caao.com.tabs.calendar.CalendarViewFactory.createCalendarView(CalendarViewFactory.java:35)
		assertNotNull(result);
	}

	/**
	 * Run the CalendarView createCalendarView2() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 5/1/11 6:24 PM
	 */
	@Test
	public void testCreateCalendarView2_1()
		throws Exception {

		CalendarView result = CalendarViewFactory.createCalendarView2();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.RuntimeException: Stub!
		//       at android.content.Context.<init>(Context.java:4)
		//       at android.content.ContextWrapper.<init>(ContextWrapper.java:5)
		//       at android.view.ContextThemeWrapper.<init>(ContextThemeWrapper.java:5)
		//       at android.app.Activity.<init>(Activity.java:6)
		//       at android.app.ActivityGroup.<init>(ActivityGroup.java:5)
		//       at android.app.TabActivity.<init>(TabActivity.java:5)
		//       at caao.com.Main_activity.<init>(Main_activity.java:57)
		//       at caao.com.Main_activityFactory.createMain_activity(Main_activityFactory.java:29)
		//       at caao.com.tabs.calendar.CalendarViewFactory.createCalendarView2(CalendarViewFactory.java:45)
		assertNotNull(result);
	}

	/**
	 * Run the CalendarView createCalendarView3() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 5/1/11 6:24 PM
	 */
	@Test
	public void testCreateCalendarView3_1()
		throws Exception {

		CalendarView result = CalendarViewFactory.createCalendarView3();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.RuntimeException: Stub!
		//       at android.content.Context.<init>(Context.java:4)
		//       at android.content.ContextWrapper.<init>(ContextWrapper.java:5)
		//       at android.view.ContextThemeWrapper.<init>(ContextThemeWrapper.java:5)
		//       at android.app.Activity.<init>(Activity.java:6)
		//       at android.app.ActivityGroup.<init>(ActivityGroup.java:5)
		//       at android.app.TabActivity.<init>(TabActivity.java:5)
		//       at caao.com.Main_activity.<init>(Main_activity.java:57)
		//       at caao.com.Main_activityFactory.createMain_activity(Main_activityFactory.java:29)
		//       at caao.com.tabs.calendar.CalendarViewFactory.createCalendarView3(CalendarViewFactory.java:55)
		assertNotNull(result);
	}

	/**
	 * Run the CalendarView createCalendarView4() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 5/1/11 6:24 PM
	 */
	@Test
	public void testCreateCalendarView4_1()
		throws Exception {

		CalendarView result = CalendarViewFactory.createCalendarView4();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.RuntimeException: Stub!
		//       at android.content.Context.<init>(Context.java:4)
		//       at android.content.ContextWrapper.<init>(ContextWrapper.java:5)
		//       at android.view.ContextThemeWrapper.<init>(ContextThemeWrapper.java:5)
		//       at android.app.Activity.<init>(Activity.java:6)
		//       at android.app.ListActivity.<init>(ListActivity.java:5)
		//       at caao.com.Settings_activity.<init>(Settings_activity.java:33)
		//       at caao.com.Settings_activityFactory.createSettings_activity(Settings_activityFactory.java:29)
		//       at caao.com.tabs.calendar.CalendarViewFactory.createCalendarView4(CalendarViewFactory.java:65)
		assertNotNull(result);
	}

	/**
	 * Run the CalendarView createCalendarView5() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 5/1/11 6:24 PM
	 */
	@Test
	public void testCreateCalendarView5_1()
		throws Exception {

		CalendarView result = CalendarViewFactory.createCalendarView5();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.RuntimeException: Stub!
		//       at android.content.Context.<init>(Context.java:4)
		//       at android.content.ContextWrapper.<init>(ContextWrapper.java:5)
		//       at android.app.Service.<init>(Service.java:6)
		//       at caao.com.service.caao_service.<init>(caao_service.java:38)
		//       at caao.com.service.caao_serviceFactory.createcaao_service(caao_serviceFactory.java:29)
		//       at caao.com.tabs.calendar.CalendarViewFactory.createCalendarView5(CalendarViewFactory.java:75)
		assertNotNull(result);
	}

	/**
	 * Run the CalendarView createCalendarView6() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 5/1/11 6:24 PM
	 */
	@Test
	public void testCreateCalendarView6_1()
		throws Exception {

		CalendarView result = CalendarViewFactory.createCalendarView6();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.RuntimeException: Stub!
		//       at android.content.Context.<init>(Context.java:4)
		//       at android.content.ContextWrapper.<init>(ContextWrapper.java:5)
		//       at android.view.ContextThemeWrapper.<init>(ContextThemeWrapper.java:5)
		//       at android.app.Activity.<init>(Activity.java:6)
		//       at android.app.ListActivity.<init>(ListActivity.java:5)
		//       at android.preference.PreferenceActivity.<init>(PreferenceActivity.java:5)
		//       at caao.com.settings_activities.Advanced_settings.<init>(Advanced_settings.java:22)
		//       at caao.com.settings_activities.Advanced_settingsFactory.createAdvanced_settings(Advanced_settingsFactory.java:29)
		//       at caao.com.tabs.calendar.CalendarViewFactory.createCalendarView6(CalendarViewFactory.java:85)
		assertNotNull(result);
	}

	/**
	 * Perform pre-test initialization.
	 *
	 * @throws Exception
	 *         if the initialization fails for some reason
	 *
	 * @generatedBy CodePro at 5/1/11 6:24 PM
	 */
	@Before
	public void setUp()
		throws Exception {
		// add additional set up code here
	}

	/**
	 * Perform post-test clean-up.
	 *
	 * @throws Exception
	 *         if the clean-up fails for some reason
	 *
	 * @generatedBy CodePro at 5/1/11 6:24 PM
	 */
	@After
	public void tearDown()
		throws Exception {
		// Add additional tear down code here
	}

	/**
	 * Launch the test.
	 *
	 * @param args the command line arguments
	 *
	 * @generatedBy CodePro at 5/1/11 6:24 PM
	 */
	public static void main(String[] args) {
		new org.junit.runner.JUnitCore().run(CalendarViewFactoryTest.class);
	}
}